### ISSUE TITLE
Change type of input parameter

### ISSUE THREAD

**Issue by remcohaszing** [vfile/vfile-location#12]
### Initial checklist

- [X] I read the [support docs](https://github.com/vfile/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/vfile/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/vfile/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Avfile&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently the type of the input argument is `VFile | Value`. This makes sense considering this package is called `vfile-location`. However, it actually doesn’t use anything specific to vfile. It’s also useful outside of the vfile ecosystem. It coerces the type to string, then runs string operations. Really this function accepts anything that has a nice `toString()` implementation, which `VFile` and `Value` happen to do.

A downside of accepting vfile specific values in type definitions, is that it pulls in a dependency on `vfile`. This means it’s also affected by the `vfile` release cycle.

### Solution

Change the input type to `unknown`. This way anything can be passed, including `VFile`, `Value`, or other third party objects that has a nice `toString()` implementation.

### Alternatives

1. Change the input type to `string`. The downside is that according to TypeScript, this means `VFile` is no longer accepted.
2. Create a new library that does everything this package does, except to string coercion. `vfile-location` could pass the coerced value to that function.
3. Keep this as-is. I mainly wanted to put this up for discussion.

**Comment by remcohaszing** [comment]
Ok, let’s close this then.

**Comment by wooorm** [comment]
I don't feel very strongly about these things though! :)
